version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_eventos
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Javi2004
      POSTGRES_DB: prueba
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eventos_net

  api:
    build: ./backend
    container_name: api_eventos
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Javi2004
      DB_NAME: prueba
    networks:
      - eventos_net

networks:
  eventos_net:
